# superpower-clockless standalone Windows installer
# Downloads bootstrap script and runs it, or installs superpower-clockless directly

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

Write-Host "=== superpower-clockless Windows Installer ===" -ForegroundColor Cyan
Write-Host ""

# Detect admin rights
function Test-Admin {
    $currentUser = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($currentUser)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

# Check Python
function Get-PythonVersion {
    try {
        $version = python --version 2>&1
        if ($version -match "Python (\d+)\.(\d+)") {
            return @{
                major = [int]$Matches[1]
                minor = [int]$Matches[2]
                ok = ($matches[1] -eq 3 -and $matches[2] -ge 10)
            }
        }
    } catch {}
    return @{ ok = $false }
}

# Download and run bootstrap
function Install-Bootstrap {
    Write-Host "[installer] Downloading bootstrap.ps1..." -ForegroundColor Yellow
    try {
        $script = Invoke-RestMethod -Uri "https://raw.githubusercontent.com/YeLuo45/superpower-clockless/main/bootstrap.ps1" -TimeoutSec 30
        $scriptPath = "$env:TEMP\superpower-clockless-bootstrap.ps1"
        Set-Content -Path $scriptPath -Value $script -Encoding UTF8
        Write-Host "[installer] Running bootstrap script..." -ForegroundColor Yellow
        & $scriptPath
        Remove-Item $scriptPath -Force -EA SilentlyContinue
        return $true
    } catch {
        Write-Host "[installer] Bootstrap script not found, using direct install..." -ForegroundColor Yellow
        return $false
    }
}

# Direct install (no bootstrap.ps1 available)
function Install-Direct {
    Write-Host "[installer] Checking Python 3.10+..." -ForegroundColor Yellow
    $py = Get-PythonVersion
    if (-not $py.ok) {
        Write-Host "[installer] Python 3.10+ not found. Please install Python from:" -ForegroundColor Red
        Write-Host "  https://www.python.org/downloads/" -ForegroundColor Cyan
        Write-Host "  OR: winget install Python.Python.3.11" -ForegroundColor Cyan
        return $false
    }
    Write-Host "[installer] Python $($py.major).$($py.minor) found. Good!" -ForegroundColor Green

    Write-Host "[installer] Creating virtual environment..." -ForegroundColor Yellow
    $venvDir = "$env:USERPROFILE\.superpower-clockless\venv"
    python -m venv $venvDir

    Write-Host "[installer] Upgrading pip..." -ForegroundColor Yellow
    & "$venvDir\Scripts\pip.exe" install --upgrade pip -q

    Write-Host "[installer] Installing superpower-clockless..." -ForegroundColor Yellow
    & "$venvDir\Scripts\pip.exe" install superpower-clockless -q

    Write-Host "[installer] Writing env.bat..." -ForegroundColor Yellow
    $envBat = "$env:USERPROFILE\.superpower-clockless\env.bat"
    $envDir = Split-Path $envBat -Parent
    if (-not (Test-Path $envDir)) { New-Item -ItemType Directory -Path $envDir -Force | Out-Null }

    @"
@echo off
REM superpower-clockless environment
REM Auto-generated by install.ps1

REM ai-superpower API key (REQUIRED)
REM Get your key from: https://github.com/YeLuo45/ai-superpower
REM set "AI_SUPERPOWER_API_KEY=your-key-here"

REM Activate venv
if exist "%USERPROFILE%\.superpower-clockless\venv\Scripts\activate.bat" (
    call "%USERPROFILE%\.superpower-clockless\venv\Scripts\activate.bat"
)
"@ | Set-Content -Path $envBat -Encoding ASCII

    Write-Host ""
    Write-Host "=== Installation Complete ===" -ForegroundColor Green
    Write-Host ""
    Write-Host "Next steps:" -ForegroundColor Cyan
    Write-Host "1. Edit $envBat and add your API key:" -ForegroundColor White
    Write-Host '   set "AI_SUPERPOWER_API_KEY=<your-key>"'
    Write-Host ""
    Write-Host "2. Run: .\.superpower-clockless\env.bat" -ForegroundColor White
    Write-Host ""
    Write-Host "3. Verify: superpower-clockless agents" -ForegroundColor White
    return $true
}

# Main
$py = Get-PythonVersion
if ($py.ok) {
    Write-Host "[installer] Python $($py.major).$($py.minor) found. Using direct install." -ForegroundColor Green
    $ok = Install-Direct
} else {
    Write-Host "[installer] No Python found. Attempting bootstrap..." -ForegroundColor Yellow
    $ok = Install-Direct
}

if (-not $ok) {
    Write-Host ""
    Write-Host "Installation completed with warnings." -ForegroundColor Yellow
    Write-Host "Please ensure Python 3.10+ is installed manually." -ForegroundColor Yellow
}