#!/usr/bin/env bash
# superpower-clockless bootstrap script
# Detects OS, installs Python 3 if missing, clones repo, sets up superpower-clockless in a venv

set -e

echo "=== superpower-clockless bootstrap ==="
echo ""

# Detect OS
detect_os() {
    if [ "$(uname)" = "Darwin" ]; then
        echo "macos"
    elif [ -f /etc/os-release ]; then
        . /etc/os-release
        case "$ID" in
            ubuntu|debian|linuxmint)
                echo "debian"
                ;;
            fedora|rhel|centos|rocky|almalinux)
                echo "rhel"
                ;;
            arch|manjaro)
                echo "arch"
                ;;
            alpine)
                echo "alpine"
                ;;
            *)
                echo "unknown"
                ;;
        esac
    else
        echo "unknown"
    fi
}

# Check if Python 3.10+ is available
check_python() {
    if command -v python3 &>/dev/null; then
        PYTHON_MAJOR=$(python3 -c 'import sys; print(sys.version_info[0])')
        PYTHON_MINOR=$(python3 -c 'import sys; print(sys.version_info[1])')
        if [ "$PYTHON_MAJOR" -eq 3 ] && [ "$PYTHON_MINOR" -ge 10 ]; then
            echo "ok"
            return 0
        fi
    fi
    echo "missing"
    return 1
}

# Install Python based on OS
install_python() {
    OS=$(detect_os)
    echo "[bootstrap] OS detected: $OS"

    case "$OS" in
        macos)
            echo "[bootstrap] Installing Python 3 via brew..."
            if ! command -v brew &>/dev/null; then
                echo "[bootstrap] ERROR: Homebrew not found. Please install Homebrew first: https://brew.sh"
                exit 1
            fi
            brew install python@3.11 python@3.12 2>/dev/null || brew install python@3.11
            ;;
        debian)
            echo "[bootstrap] Installing Python 3 via apt..."
            export DEBIAN_FRONTEND=noninteractive
            apt-get update -qq
            apt-get install -y -qq python3.11 python3.11-venv python3-pip curl git
            ;;
        rhel)
            echo "[bootstrap] Installing Python 3 via dnf/yum..."
            dnf install -y -q python311 python311-venv python3-pip curl git 2>/dev/null || \
            yum install -y -q python3.11 python3-venv python3-pip curl git
            ;;
        arch)
            echo "[bootstrap] Installing Python 3 via pacman..."
            pacman -Sy --noconfirm python python-pip curl git
            ;;
        alpine)
            echo "[bootstrap] Installing Python 3 via apk..."
            apk add --no-cache python3 py3-pip curl git
            ;;
        unknown)
            echo "[bootstrap] ERROR: Could not detect OS. Please install Python 3.10+ manually."
            exit 1
            ;;
    esac

    if ! command -v python3 &>/dev/null; then
        echo "[bootstrap] ERROR: Python 3 installation failed."
        exit 1
    fi
}

# Clone superpower-clockless repo locally
clone_repo() {
    LOCAL_DIR="$HOME/superpower-clockless"
    if [ -d "$LOCAL_DIR" ]; then
        echo "[bootstrap] Repo already exists at $LOCAL_DIR, pulling latest..."
        git -C "$LOCAL_DIR" pull origin main || echo "[bootstrap] git pull failed, using existing files"
    else
        echo "[bootstrap] Cloning superpower-clockless repo..."
        git clone https://github.com/YeLuo45/superpower-clockless.git "$LOCAL_DIR"
    fi
}

# Create venv and install superpower-clockless from local source
setup_venv() {
    VENV_DIR="$HOME/.superpower-clockless/venv"
    LOCAL_DIR="$HOME/superpower-clockless"

    echo "[bootstrap] Creating virtual environment at $VENV_DIR..."
    python3 -m venv "$VENV_DIR"
    echo "[bootstrap] Upgrading pip..."
    "$VENV_DIR/bin/pip" install --upgrade pip --timeout 60 -q

    echo "[bootstrap] Installing superpower-clockless from local source: $LOCAL_DIR"
    "$VENV_DIR/bin/pip" install -e "$LOCAL_DIR" --timeout 60 -q

    if ! "$VENV_DIR/bin/superpower-clockless" --version &>/dev/null; then
        echo "[bootstrap] ERROR: superpower-clockless installation failed."
        exit 1
    fi
}

# Write env file
write_env() {
    ENV_FILE="$HOME/.superpower-clockless/env"
    mkdir -p "$(dirname "$ENV_FILE")"
    echo "[bootstrap] Writing environment file: $ENV_FILE"

    cat > "$ENV_FILE" << 'ENVFILE'
# superpower-clockless environment
# Auto-generated by bootstrap.sh

# ai-superpower API key (REQUIRED)
# Get your key from: https://github.com/YeLuo45/ai-superpower
# export AI_SUPERPOWER_API_KEY="your-key-here"

# ai-superpower server URL (default: http://127.0.0.1:8000)
# export AI_SUPERPOWER_URL="http://127.0.0.1:8000"

# Activate venv
if [ -f "$HOME/.superpower-clockless/venv/bin/activate" ]; then
    source "$HOME/.superpower-clockless/venv/bin/activate"
fi
ENVFILE

    chmod 600 "$ENV_FILE"
}

# Main
main() {
    echo "[bootstrap] Detecting Python 3.10+..."
    if ! check_python; then
        echo "[bootstrap] Python 3.10+ not found. Installing..."
        install_python
    else
        echo "[bootstrap] Python 3.10+ found."
    fi

    clone_repo
    setup_venv
    write_env

    echo ""
    echo "=== bootstrap complete ==="
    echo ""
    echo "Next steps:"
    echo "1. Edit $HOME/.superpower-clockless/env and add your API key:"
    echo "   export AI_SUPERPOWER_API_KEY=\"<your-key>\""
    echo ""
    echo "2. Add to your shell profile:"
    echo "   Unix/macOS: echo 'source ~/.superpower-clockless/env' >> ~/.bashrc"
    echo "   Then restart terminal or run: source ~/.bashrc"
    echo ""
    echo "3. Verify installation:"
    echo "   superpower-clockless agents"
    echo ""
}

main "$@"