# superpower-clockless Windows bootstrap installer
# Clones repo locally, installs from source — no PyPI needed

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

Write-Host "=== superpower-clockless Windows Installer ===" -ForegroundColor Cyan
Write-Host ""

$LOCAL_DIR = "$env:USERPROFILE\superpower-clockless"
$VENV_DIR = "$env:USERPROFILE\.superpower-clockless\venv"

# Check Python
function Get-PythonVersion {
    try {
        $version = python --version 2>&1
        if ($version -match "Python (\d+)\.(\d+)") {
            return @{
                major = [int]$Matches[1]
                minor = [int]$Matches[2]
                ok = ($Matches[1] -eq 3 -and $Matches[2] -ge 10)
            }
        }
    } catch {}
    return @{ ok = $false }
}

# Clone or update repo
function Clone-Repo {
    if (Test-Path $LOCAL_DIR) {
        Write-Host "[installer] Repo exists at $LOCAL_DIR, pulling latest..." -ForegroundColor Yellow
        Set-Location $LOCAL_DIR
        git pull origin main 2>$null | Out-Null
    } else {
        Write-Host "[installer] Cloning superpower-clockless repo..." -ForegroundColor Yellow
        git clone https://github.com/YeLuo45/superpower-clockless.git $LOCAL_DIR
        Set-Location $LOCAL_DIR
    }
}

# Install from local source
function Install-Local {
    Write-Host "[installer] Creating virtual environment at $VENV_DIR..." -ForegroundColor Yellow
    if (Test-Path $VENV_DIR) {
        Remove-Item -Path $VENV_DIR -Recurse -Force
    }
    python -m venv $VENV_DIR

    Write-Host "[installer] Upgrading pip..." -ForegroundColor Yellow
    & "$VENV_DIR\Scripts\pip.exe" install --upgrade pip --timeout 60 -q 2>$null

    Write-Host "[installer] Installing superpower-clockless from local source..." -ForegroundColor Yellow
    Set-Location $LOCAL_DIR
    $venvPip = "$VENV_DIR\Scripts\pip.exe"
    $output = & $venvPip install -e "$LOCAL_DIR" --timeout 60 -q 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Host "[installer] pip install failed. Output:" -ForegroundColor Red
        Write-Host $output
        return $false
    }

    if (-not (Test-Path "$VENV_DIR\Scripts\superpower-clockless.exe")) {
        Write-Host "[installer] ERROR: superpower-clockless.exe not found after install." -ForegroundColor Red
        return $false
    }
    return $true
}

# Write env.bat
function Write-EnvBat {
    $envBat = "$env:USERPROFILE\.superpower-clockless\env.bat"
    $envDir = Split-Path $envBat -Parent
    if (-not (Test-Path $envDir)) { New-Item -ItemType Directory -Path $envDir -Force | Out-Null }

    @"
@echo off
REM superpower-clockless environment
REM Auto-generated by bootstrap.ps1

REM ai-superpower API key (REQUIRED)
REM Get your key from: https://github.com/YeLuo45/ai-superpower
REM set "AI_SUPERPOWER_API_KEY=your-key-here"

REM Activate venv
if exist "%USERPROFILE%\.superpower-clockless\venv\Scripts\activate.bat" (
    call "%USERPROFILE%\.superpower-clockless\venv\Scripts\activate.bat"
)
"@ | Set-Content -Path $envBat -Encoding ASCII
}

# Main
$py = Get-PythonVersion
if (-not $py.ok) {
    Write-Host "[installer] ERROR: Python 3.10+ not found. Please install Python first:" -ForegroundColor Red
    Write-Host "  https://www.python.org/downloads/" -ForegroundColor Cyan
    Write-Host "  OR: winget install Python.Python.3.11" -ForegroundColor Cyan
    exit 1
}

Write-Host "[installer] Python $($py.major).$($py.minor) found. Good!" -ForegroundColor Green

try {
    Clone-Repo
    $ok = Install-Local
    if (-not $ok) { throw "Install-Local failed" }
    Write-EnvBat

    Write-Host ""
    Write-Host "=== Installation Complete ===" -ForegroundColor Green
    Write-Host ""
    Write-Host "Next steps:" -ForegroundColor Cyan
    Write-Host "1. Edit $env:USERPROFILE\.superpower-clockless\env.bat and add your API key:" -ForegroundColor White
    Write-Host '   set "AI_SUPERPOWER_API_KEY=<your-key>"'
    Write-Host ""
    Write-Host "2. Run: .\.superpower-clockless\env.bat" -ForegroundColor White
    Write-Host ""
    Write-Host "3. Verify: superpower-clockless agents" -ForegroundColor White
} catch {
    Write-Host ""
    Write-Host "[installer] ERROR: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host "Installation incomplete. Please try again or install manually." -ForegroundColor Yellow
    exit 1
}